# 当前workflow配置的名称
name: Sync
# 任务触发时机，这里是在向github上的master分支提交代码以及提交PR时进行触发
on:
  push: # 触发条件
    branches: [main, master] # 分支名
  workflow_dispatch:
# 需要触发的任务信息，一个workflow可以包含多个的job，这里只有一个名为build的job
jobs:
  deploy_gh_pages:
    # 当前job需要运行在的系统环境
    runs-on: ubuntu-latest
    # 实现一个job需要执行的各个步骤
    steps:
      - name: Github Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:yequanrui/CloudNotes.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:yequanrui/CloudNotes.git
